import type { LabConfig } from '../toolkit/types';

export const LAB_REGISTRY: LabConfig[] = [
  {
    id: 'foundations',
    title: 'Lab 1 — Foundations',
    shortTitle: 'Foundations',
    description: 'Philosophical and scientific mission. Systemic synthesis whitepapers and dissertation-derived AI integration theories.',
    components: ['theory-docs', 'whitepaper-viewer'],
    theme: 'gold',
    ai_enabled: false,
    author: 'ISRD Core',
    path: '/lab/foundations',
  },
  {
    id: 'foundry',
    title: 'Lab 2 — Foundry & Training',
    shortTitle: 'Foundry',
    description: 'The Engine Room. Toolkit API docs, Academy learning paths, and the Sim-Registry catalog.',
    components: ['api-docs', 'academy', 'sim-registry'],
    theme: 'cyan',
    ai_enabled: true,
    author: 'ISRD Core',
    path: '/lab/foundry',
  },
  {
    id: 'bio-systemics',
    title: 'Lab 3 — Bio-Systemics',
    shortTitle: 'Bio-Systemics',
    description: 'Interactive medical simulator. ME/CFS outbreak model, brainstem pacemaker dynamics, and post-viral syndrome research.',
    components: ['mecfs-simulator', 'brainstem-pacemaker', 'metabolic-gauge'],
    theme: 'blue-pulse',
    ai_enabled: true,
    author: 'ISRD Core',
    path: '/lab/bio-systemics',
  },
  {
    id: 'literary-systemics',
    title: 'Lab 4 — Literary Systemics',
    shortTitle: 'Literary',
    description: 'AI-integrative writing impact simulator. Author strategy and process analysis through a systemic lens.',
    components: ['writing-impact', 'author-strategy', 'loop-indicator'],
    theme: 'amber',
    ai_enabled: true,
    author: 'ISRD Core',
    path: '/lab/literary-systemics',
  },
  {
    id: 'global-futurism',
    title: 'Lab 5 — Global Futurism',
    shortTitle: 'Futurism',
    description: 'Macro-systemic trend simulator. Socio-economic tipping points and civilizational attractor dynamics.',
    components: ['tipping-point-sim', 'trend-forecast', 'basin-visualizer'],
    theme: 'violet',
    ai_enabled: true,
    author: 'ISRD Core',
    path: '/lab/global-futurism',
  },
];

export const THEME_ACCENTS: Record<string, string> = {
  gold:        '#d4a847',
  cyan:        '#3a8fa8',
  'blue-pulse':'#3a6fa8',
  amber:       '#c87832',
  violet:      '#7a5ac8',
};
